"""Static data for all 48 Mega Evolutions (46 species, Charizard and Mewtwo have 2 each).

Used by transformers.build_mega_evolution_documents() to generate:
- A summary doc listing all megas (for "quante mega evoluzioni esistono?")
- Per-Pokemon docs with full details (for "parlami di Mega Charizard X")

Data sourced from Bulbapedia / Serebii. Stats are post-mega transformation.
"""

MEGA_EVOLUTIONS: list[dict] = [
    # --- Gen 1 Pokemon ---
    {
        "pokemon_id": 3, "pokemon": "Venusaur",
        "mega_name_en": "Mega Venusaur", "mega_name_it": "Mega Venusaur",
        "type1": "Grass", "type2": "Poison",
        "type1_it": "Erba", "type2_it": "Veleno",
        "ability": "Thick Fat", "ability_it": "Grassospesso",
        "mega_stone": "Venusaurite", "mega_stone_it": "Venusaurite",
        "stats": {"hp": 80, "atk": 100, "def": 123, "spa": 122, "spd": 120, "spe": 80},
        "bst": 625,
    },
    {
        "pokemon_id": 6, "pokemon": "Charizard",
        "mega_name_en": "Mega Charizard X", "mega_name_it": "Mega Charizard X",
        "type1": "Fire", "type2": "Dragon",
        "type1_it": "Fuoco", "type2_it": "Drago",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Charizardite X", "mega_stone_it": "Charizardite X",
        "stats": {"hp": 78, "atk": 130, "def": 111, "spa": 130, "spd": 85, "spe": 100},
        "bst": 634,
    },
    {
        "pokemon_id": 6, "pokemon": "Charizard",
        "mega_name_en": "Mega Charizard Y", "mega_name_it": "Mega Charizard Y",
        "type1": "Fire", "type2": "Flying",
        "type1_it": "Fuoco", "type2_it": "Volante",
        "ability": "Drought", "ability_it": "Siccita",
        "mega_stone": "Charizardite Y", "mega_stone_it": "Charizardite Y",
        "stats": {"hp": 78, "atk": 104, "def": 78, "spa": 159, "spd": 115, "spe": 100},
        "bst": 634,
    },
    {
        "pokemon_id": 9, "pokemon": "Blastoise",
        "mega_name_en": "Mega Blastoise", "mega_name_it": "Mega Blastoise",
        "type1": "Water", "type2": "",
        "type1_it": "Acqua", "type2_it": "",
        "ability": "Mega Launcher", "ability_it": "Megalancio",
        "mega_stone": "Blastoisinite", "mega_stone_it": "Blastoisinite",
        "stats": {"hp": 79, "atk": 103, "def": 120, "spa": 135, "spd": 115, "spe": 78},
        "bst": 630,
    },
    {
        "pokemon_id": 15, "pokemon": "Beedrill",
        "mega_name_en": "Mega Beedrill", "mega_name_it": "Mega Beedrill",
        "type1": "Bug", "type2": "Poison",
        "type1_it": "Coleottero", "type2_it": "Veleno",
        "ability": "Adaptability", "ability_it": "Adattabilita",
        "mega_stone": "Beedrillite", "mega_stone_it": "Beedrillite",
        "stats": {"hp": 65, "atk": 150, "def": 40, "spa": 15, "spd": 80, "spe": 145},
        "bst": 495,
    },
    {
        "pokemon_id": 18, "pokemon": "Pidgeot",
        "mega_name_en": "Mega Pidgeot", "mega_name_it": "Mega Pidgeot",
        "type1": "Normal", "type2": "Flying",
        "type1_it": "Normale", "type2_it": "Volante",
        "ability": "No Guard", "ability_it": "Nullaguardia",
        "mega_stone": "Pidgeotite", "mega_stone_it": "Pidgeotite",
        "stats": {"hp": 83, "atk": 80, "def": 80, "spa": 135, "spd": 80, "spe": 121},
        "bst": 579,
    },
    {
        "pokemon_id": 65, "pokemon": "Alakazam",
        "mega_name_en": "Mega Alakazam", "mega_name_it": "Mega Alakazam",
        "type1": "Psychic", "type2": "",
        "type1_it": "Psico", "type2_it": "",
        "ability": "Trace", "ability_it": "Traccia",
        "mega_stone": "Alakazite", "mega_stone_it": "Alakazamite",
        "stats": {"hp": 55, "atk": 50, "def": 65, "spa": 175, "spd": 105, "spe": 150},
        "bst": 600,
    },
    {
        "pokemon_id": 80, "pokemon": "Slowbro",
        "mega_name_en": "Mega Slowbro", "mega_name_it": "Mega Slowbro",
        "type1": "Water", "type2": "Psychic",
        "type1_it": "Acqua", "type2_it": "Psico",
        "ability": "Shell Armor", "ability_it": "Guscioscudo",
        "mega_stone": "Slowbronite", "mega_stone_it": "Slowbronite",
        "stats": {"hp": 95, "atk": 75, "def": 180, "spa": 130, "spd": 80, "spe": 30},
        "bst": 590,
    },
    {
        "pokemon_id": 94, "pokemon": "Gengar",
        "mega_name_en": "Mega Gengar", "mega_name_it": "Mega Gengar",
        "type1": "Ghost", "type2": "Poison",
        "type1_it": "Spettro", "type2_it": "Veleno",
        "ability": "Shadow Tag", "ability_it": "Pedinombra",
        "mega_stone": "Gengarite", "mega_stone_it": "Gengarite",
        "stats": {"hp": 60, "atk": 65, "def": 80, "spa": 170, "spd": 95, "spe": 130},
        "bst": 600,
    },
    {
        "pokemon_id": 115, "pokemon": "Kangaskhan",
        "mega_name_en": "Mega Kangaskhan", "mega_name_it": "Mega Kangaskhan",
        "type1": "Normal", "type2": "",
        "type1_it": "Normale", "type2_it": "",
        "ability": "Parental Bond", "ability_it": "Amorefiliale",
        "mega_stone": "Kangaskhanite", "mega_stone_it": "Kangaskhanite",
        "stats": {"hp": 105, "atk": 125, "def": 100, "spa": 60, "spd": 100, "spe": 100},
        "bst": 590,
    },
    {
        "pokemon_id": 127, "pokemon": "Pinsir",
        "mega_name_en": "Mega Pinsir", "mega_name_it": "Mega Pinsir",
        "type1": "Bug", "type2": "Flying",
        "type1_it": "Coleottero", "type2_it": "Volante",
        "ability": "Aerilate", "ability_it": "Aerificazione",
        "mega_stone": "Pinsirite", "mega_stone_it": "Pinsirite",
        "stats": {"hp": 65, "atk": 155, "def": 120, "spa": 65, "spd": 90, "spe": 105},
        "bst": 600,
    },
    {
        "pokemon_id": 130, "pokemon": "Gyarados",
        "mega_name_en": "Mega Gyarados", "mega_name_it": "Mega Gyarados",
        "type1": "Water", "type2": "Dark",
        "type1_it": "Acqua", "type2_it": "Buio",
        "ability": "Mold Breaker", "ability_it": "Rompiforma",
        "mega_stone": "Gyaradosite", "mega_stone_it": "Gyaradosite",
        "stats": {"hp": 95, "atk": 155, "def": 109, "spa": 70, "spd": 130, "spe": 81},
        "bst": 640,
    },
    {
        "pokemon_id": 142, "pokemon": "Aerodactyl",
        "mega_name_en": "Mega Aerodactyl", "mega_name_it": "Mega Aerodactyl",
        "type1": "Rock", "type2": "Flying",
        "type1_it": "Roccia", "type2_it": "Volante",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Aerodactylite", "mega_stone_it": "Aerodactylite",
        "stats": {"hp": 80, "atk": 135, "def": 85, "spa": 70, "spd": 95, "spe": 150},
        "bst": 615,
    },
    {
        "pokemon_id": 150, "pokemon": "Mewtwo",
        "mega_name_en": "Mega Mewtwo X", "mega_name_it": "Mega Mewtwo X",
        "type1": "Psychic", "type2": "Fighting",
        "type1_it": "Psico", "type2_it": "Lotta",
        "ability": "Steadfast", "ability_it": "Cuordeciso",
        "mega_stone": "Mewtwonite X", "mega_stone_it": "Mewtwonite X",
        "stats": {"hp": 106, "atk": 190, "def": 100, "spa": 154, "spd": 100, "spe": 130},
        "bst": 780,
    },
    {
        "pokemon_id": 150, "pokemon": "Mewtwo",
        "mega_name_en": "Mega Mewtwo Y", "mega_name_it": "Mega Mewtwo Y",
        "type1": "Psychic", "type2": "",
        "type1_it": "Psico", "type2_it": "",
        "ability": "Insomnia", "ability_it": "Insonnia",
        "mega_stone": "Mewtwonite Y", "mega_stone_it": "Mewtwonite Y",
        "stats": {"hp": 106, "atk": 150, "def": 70, "spa": 194, "spd": 120, "spe": 140},
        "bst": 780,
    },
    # --- Gen 2 Pokemon ---
    {
        "pokemon_id": 181, "pokemon": "Ampharos",
        "mega_name_en": "Mega Ampharos", "mega_name_it": "Mega Ampharos",
        "type1": "Electric", "type2": "Dragon",
        "type1_it": "Elettro", "type2_it": "Drago",
        "ability": "Mold Breaker", "ability_it": "Rompiforma",
        "mega_stone": "Ampharosite", "mega_stone_it": "Ampharosite",
        "stats": {"hp": 90, "atk": 95, "def": 105, "spa": 165, "spd": 110, "spe": 45},
        "bst": 610,
    },
    {
        "pokemon_id": 208, "pokemon": "Steelix",
        "mega_name_en": "Mega Steelix", "mega_name_it": "Mega Steelix",
        "type1": "Steel", "type2": "Ground",
        "type1_it": "Acciaio", "type2_it": "Terra",
        "ability": "Sand Force", "ability_it": "Sabbiaforza",
        "mega_stone": "Steelixite", "mega_stone_it": "Steelixite",
        "stats": {"hp": 75, "atk": 125, "def": 230, "spa": 55, "spd": 95, "spe": 30},
        "bst": 610,
    },
    {
        "pokemon_id": 212, "pokemon": "Scizor",
        "mega_name_en": "Mega Scizor", "mega_name_it": "Mega Scizor",
        "type1": "Bug", "type2": "Steel",
        "type1_it": "Coleottero", "type2_it": "Acciaio",
        "ability": "Technician", "ability_it": "Tecnico",
        "mega_stone": "Scizorite", "mega_stone_it": "Scizorite",
        "stats": {"hp": 70, "atk": 150, "def": 140, "spa": 65, "spd": 100, "spe": 75},
        "bst": 600,
    },
    {
        "pokemon_id": 214, "pokemon": "Heracross",
        "mega_name_en": "Mega Heracross", "mega_name_it": "Mega Heracross",
        "type1": "Bug", "type2": "Fighting",
        "type1_it": "Coleottero", "type2_it": "Lotta",
        "ability": "Skill Link", "ability_it": "Abillegame",
        "mega_stone": "Heracronite", "mega_stone_it": "Heracrossite",
        "stats": {"hp": 80, "atk": 185, "def": 115, "spa": 40, "spd": 105, "spe": 75},
        "bst": 600,
    },
    {
        "pokemon_id": 229, "pokemon": "Houndoom",
        "mega_name_en": "Mega Houndoom", "mega_name_it": "Mega Houndoom",
        "type1": "Dark", "type2": "Fire",
        "type1_it": "Buio", "type2_it": "Fuoco",
        "ability": "Solar Power", "ability_it": "Solarpotere",
        "mega_stone": "Houndoominite", "mega_stone_it": "Houndoomite",
        "stats": {"hp": 75, "atk": 90, "def": 90, "spa": 140, "spd": 90, "spe": 115},
        "bst": 600,
    },
    {
        "pokemon_id": 248, "pokemon": "Tyranitar",
        "mega_name_en": "Mega Tyranitar", "mega_name_it": "Mega Tyranitar",
        "type1": "Rock", "type2": "Dark",
        "type1_it": "Roccia", "type2_it": "Buio",
        "ability": "Sand Stream", "ability_it": "Sabbiafiume",
        "mega_stone": "Tyranitarite", "mega_stone_it": "Tyranitarite",
        "stats": {"hp": 100, "atk": 164, "def": 150, "spa": 95, "spd": 120, "spe": 71},
        "bst": 700,
    },
    # --- Gen 3 Pokemon ---
    {
        "pokemon_id": 254, "pokemon": "Sceptile",
        "mega_name_en": "Mega Sceptile", "mega_name_it": "Mega Sceptile",
        "type1": "Grass", "type2": "Dragon",
        "type1_it": "Erba", "type2_it": "Drago",
        "ability": "Lightning Rod", "ability_it": "Parafulmine",
        "mega_stone": "Sceptilite", "mega_stone_it": "Sceptilite",
        "stats": {"hp": 70, "atk": 110, "def": 75, "spa": 145, "spd": 85, "spe": 145},
        "bst": 630,
    },
    {
        "pokemon_id": 257, "pokemon": "Blaziken",
        "mega_name_en": "Mega Blaziken", "mega_name_it": "Mega Blaziken",
        "type1": "Fire", "type2": "Fighting",
        "type1_it": "Fuoco", "type2_it": "Lotta",
        "ability": "Speed Boost", "ability_it": "Velocita",
        "mega_stone": "Blazikenite", "mega_stone_it": "Blazikenite",
        "stats": {"hp": 80, "atk": 160, "def": 80, "spa": 130, "spd": 80, "spe": 100},
        "bst": 630,
    },
    {
        "pokemon_id": 260, "pokemon": "Swampert",
        "mega_name_en": "Mega Swampert", "mega_name_it": "Mega Swampert",
        "type1": "Water", "type2": "Ground",
        "type1_it": "Acqua", "type2_it": "Terra",
        "ability": "Swift Swim", "ability_it": "Nuotovelox",
        "mega_stone": "Swampertite", "mega_stone_it": "Swampertite",
        "stats": {"hp": 100, "atk": 150, "def": 110, "spa": 95, "spd": 110, "spe": 70},
        "bst": 635,
    },
    {
        "pokemon_id": 282, "pokemon": "Gardevoir",
        "mega_name_en": "Mega Gardevoir", "mega_name_it": "Mega Gardevoir",
        "type1": "Psychic", "type2": "Fairy",
        "type1_it": "Psico", "type2_it": "Folletto",
        "ability": "Pixilate", "ability_it": "Pellefolletto",
        "mega_stone": "Gardevoirite", "mega_stone_it": "Gardevoirite",
        "stats": {"hp": 68, "atk": 85, "def": 65, "spa": 165, "spd": 135, "spe": 100},
        "bst": 618,
    },
    {
        "pokemon_id": 302, "pokemon": "Sableye",
        "mega_name_en": "Mega Sableye", "mega_name_it": "Mega Sableye",
        "type1": "Dark", "type2": "Ghost",
        "type1_it": "Buio", "type2_it": "Spettro",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Sablenite", "mega_stone_it": "Sableyite",
        "stats": {"hp": 50, "atk": 85, "def": 125, "spa": 85, "spd": 115, "spe": 20},
        "bst": 480,
    },
    {
        "pokemon_id": 303, "pokemon": "Mawile",
        "mega_name_en": "Mega Mawile", "mega_name_it": "Mega Mawile",
        "type1": "Steel", "type2": "Fairy",
        "type1_it": "Acciaio", "type2_it": "Folletto",
        "ability": "Huge Power", "ability_it": "Macroforza",
        "mega_stone": "Mawilite", "mega_stone_it": "Mawilite",
        "stats": {"hp": 50, "atk": 105, "def": 125, "spa": 55, "spd": 95, "spe": 50},
        "bst": 480,
    },
    {
        "pokemon_id": 306, "pokemon": "Aggron",
        "mega_name_en": "Mega Aggron", "mega_name_it": "Mega Aggron",
        "type1": "Steel", "type2": "",
        "type1_it": "Acciaio", "type2_it": "",
        "ability": "Filter", "ability_it": "Filtro",
        "mega_stone": "Aggronite", "mega_stone_it": "Aggronite",
        "stats": {"hp": 70, "atk": 140, "def": 230, "spa": 60, "spd": 80, "spe": 50},
        "bst": 630,
    },
    {
        "pokemon_id": 308, "pokemon": "Medicham",
        "mega_name_en": "Mega Medicham", "mega_name_it": "Mega Medicham",
        "type1": "Fighting", "type2": "Psychic",
        "type1_it": "Lotta", "type2_it": "Psico",
        "ability": "Pure Power", "ability_it": "Forzapura",
        "mega_stone": "Medichamite", "mega_stone_it": "Medichamite",
        "stats": {"hp": 60, "atk": 100, "def": 85, "spa": 80, "spd": 85, "spe": 100},
        "bst": 510,
    },
    {
        "pokemon_id": 310, "pokemon": "Manectric",
        "mega_name_en": "Mega Manectric", "mega_name_it": "Mega Manectric",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "Intimidate", "ability_it": "Prepotenza",
        "mega_stone": "Manectite", "mega_stone_it": "Manectricite",
        "stats": {"hp": 70, "atk": 75, "def": 80, "spa": 135, "spd": 80, "spe": 135},
        "bst": 575,
    },
    {
        "pokemon_id": 319, "pokemon": "Sharpedo",
        "mega_name_en": "Mega Sharpedo", "mega_name_it": "Mega Sharpedo",
        "type1": "Water", "type2": "Dark",
        "type1_it": "Acqua", "type2_it": "Buio",
        "ability": "Strong Jaw", "ability_it": "Mascelladi Ferro",
        "mega_stone": "Sharpedonite", "mega_stone_it": "Sharpedonite",
        "stats": {"hp": 70, "atk": 140, "def": 70, "spa": 110, "spd": 65, "spe": 105},
        "bst": 560,
    },
    {
        "pokemon_id": 323, "pokemon": "Camerupt",
        "mega_name_en": "Mega Camerupt", "mega_name_it": "Mega Camerupt",
        "type1": "Fire", "type2": "Ground",
        "type1_it": "Fuoco", "type2_it": "Terra",
        "ability": "Sheer Force", "ability_it": "Forzabruta",
        "mega_stone": "Cameruptite", "mega_stone_it": "Cameruptite",
        "stats": {"hp": 70, "atk": 120, "def": 100, "spa": 145, "spd": 105, "spe": 20},
        "bst": 560,
    },
    {
        "pokemon_id": 334, "pokemon": "Altaria",
        "mega_name_en": "Mega Altaria", "mega_name_it": "Mega Altaria",
        "type1": "Dragon", "type2": "Fairy",
        "type1_it": "Drago", "type2_it": "Folletto",
        "ability": "Pixilate", "ability_it": "Pellefolletto",
        "mega_stone": "Altarianite", "mega_stone_it": "Altarianite",
        "stats": {"hp": 75, "atk": 110, "def": 110, "spa": 110, "spd": 105, "spe": 80},
        "bst": 590,
    },
    {
        "pokemon_id": 354, "pokemon": "Banette",
        "mega_name_en": "Mega Banette", "mega_name_it": "Mega Banette",
        "type1": "Ghost", "type2": "",
        "type1_it": "Spettro", "type2_it": "",
        "ability": "Prankster", "ability_it": "Burla",
        "mega_stone": "Banettite", "mega_stone_it": "Banettite",
        "stats": {"hp": 64, "atk": 165, "def": 75, "spa": 93, "spd": 83, "spe": 75},
        "bst": 555,
    },
    {
        "pokemon_id": 359, "pokemon": "Absol",
        "mega_name_en": "Mega Absol", "mega_name_it": "Mega Absol",
        "type1": "Dark", "type2": "",
        "type1_it": "Buio", "type2_it": "",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Absolite", "mega_stone_it": "Absolite",
        "stats": {"hp": 65, "atk": 150, "def": 60, "spa": 115, "spd": 60, "spe": 115},
        "bst": 565,
    },
    {
        "pokemon_id": 362, "pokemon": "Glalie",
        "mega_name_en": "Mega Glalie", "mega_name_it": "Mega Glalie",
        "type1": "Ice", "type2": "",
        "type1_it": "Ghiaccio", "type2_it": "",
        "ability": "Refrigerate", "ability_it": "Pellegelo",
        "mega_stone": "Glalitite", "mega_stone_it": "Glalitite",
        "stats": {"hp": 80, "atk": 120, "def": 80, "spa": 120, "spd": 80, "spe": 100},
        "bst": 580,
    },
    {
        "pokemon_id": 373, "pokemon": "Salamence",
        "mega_name_en": "Mega Salamence", "mega_name_it": "Mega Salamence",
        "type1": "Dragon", "type2": "Flying",
        "type1_it": "Drago", "type2_it": "Volante",
        "ability": "Aerilate", "ability_it": "Aerificazione",
        "mega_stone": "Salamencite", "mega_stone_it": "Salamencite",
        "stats": {"hp": 95, "atk": 145, "def": 130, "spa": 120, "spd": 90, "spe": 120},
        "bst": 700,
    },
    {
        "pokemon_id": 376, "pokemon": "Metagross",
        "mega_name_en": "Mega Metagross", "mega_name_it": "Mega Metagross",
        "type1": "Steel", "type2": "Psychic",
        "type1_it": "Acciaio", "type2_it": "Psico",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Metagrossite", "mega_stone_it": "Metagrossite",
        "stats": {"hp": 80, "atk": 145, "def": 150, "spa": 105, "spd": 110, "spe": 110},
        "bst": 700,
    },
    {
        "pokemon_id": 380, "pokemon": "Latias",
        "mega_name_en": "Mega Latias", "mega_name_it": "Mega Latias",
        "type1": "Dragon", "type2": "Psychic",
        "type1_it": "Drago", "type2_it": "Psico",
        "ability": "Levitate", "ability_it": "Levitazione",
        "mega_stone": "Latiasite", "mega_stone_it": "Latiasite",
        "stats": {"hp": 80, "atk": 100, "def": 120, "spa": 140, "spd": 150, "spe": 110},
        "bst": 700,
    },
    {
        "pokemon_id": 381, "pokemon": "Latios",
        "mega_name_en": "Mega Latios", "mega_name_it": "Mega Latios",
        "type1": "Dragon", "type2": "Psychic",
        "type1_it": "Drago", "type2_it": "Psico",
        "ability": "Levitate", "ability_it": "Levitazione",
        "mega_stone": "Latiosite", "mega_stone_it": "Latiosite",
        "stats": {"hp": 80, "atk": 130, "def": 100, "spa": 160, "spd": 120, "spe": 110},
        "bst": 700,
    },
    # --- Gen 3 Legendaries (Primal Reversion, counted as Mega for gameplay) ---
    {
        "pokemon_id": 382, "pokemon": "Kyogre",
        "mega_name_en": "Primal Kyogre", "mega_name_it": "Kyogre Ancestrale",
        "type1": "Water", "type2": "",
        "type1_it": "Acqua", "type2_it": "",
        "ability": "Primordial Sea", "ability_it": "Mare Primordiale",
        "mega_stone": "Blue Orb", "mega_stone_it": "Gemma Blu",
        "stats": {"hp": 100, "atk": 150, "def": 90, "spa": 180, "spd": 160, "spe": 90},
        "bst": 770,
    },
    {
        "pokemon_id": 383, "pokemon": "Groudon",
        "mega_name_en": "Primal Groudon", "mega_name_it": "Groudon Ancestrale",
        "type1": "Ground", "type2": "Fire",
        "type1_it": "Terra", "type2_it": "Fuoco",
        "ability": "Desolate Land", "ability_it": "Terra Estrema",
        "mega_stone": "Red Orb", "mega_stone_it": "Gemma Rossa",
        "stats": {"hp": 100, "atk": 180, "def": 160, "spa": 150, "spd": 90, "spe": 90},
        "bst": 770,
    },
    {
        "pokemon_id": 384, "pokemon": "Rayquaza",
        "mega_name_en": "Mega Rayquaza", "mega_name_it": "Mega Rayquaza",
        "type1": "Dragon", "type2": "Flying",
        "type1_it": "Drago", "type2_it": "Volante",
        "ability": "Delta Stream", "ability_it": "Flusso Delta",
        "mega_stone": "Dragon Ascent (move)", "mega_stone_it": "Ascesa del Drago (mossa)",
        "stats": {"hp": 105, "atk": 180, "def": 100, "spa": 180, "spd": 100, "spe": 115},
        "bst": 780,
    },
    # --- Gen 4 Pokemon ---
    {
        "pokemon_id": 428, "pokemon": "Lopunny",
        "mega_name_en": "Mega Lopunny", "mega_name_it": "Mega Lopunny",
        "type1": "Normal", "type2": "Fighting",
        "type1_it": "Normale", "type2_it": "Lotta",
        "ability": "Scrappy", "ability_it": "Nerointento",
        "mega_stone": "Lopunnite", "mega_stone_it": "Lopunnite",
        "stats": {"hp": 65, "atk": 136, "def": 94, "spa": 54, "spd": 96, "spe": 135},
        "bst": 580,
    },
    {
        "pokemon_id": 445, "pokemon": "Garchomp",
        "mega_name_en": "Mega Garchomp", "mega_name_it": "Mega Garchomp",
        "type1": "Dragon", "type2": "Ground",
        "type1_it": "Drago", "type2_it": "Terra",
        "ability": "Sand Force", "ability_it": "Sabbiaforza",
        "mega_stone": "Garchompite", "mega_stone_it": "Garchompite",
        "stats": {"hp": 108, "atk": 170, "def": 115, "spa": 120, "spd": 95, "spe": 92},
        "bst": 700,
    },
    {
        "pokemon_id": 448, "pokemon": "Lucario",
        "mega_name_en": "Mega Lucario", "mega_name_it": "Mega Lucario",
        "type1": "Fighting", "type2": "Steel",
        "type1_it": "Lotta", "type2_it": "Acciaio",
        "ability": "Adaptability", "ability_it": "Adattabilita",
        "mega_stone": "Lucarionite", "mega_stone_it": "Lucarionite",
        "stats": {"hp": 70, "atk": 145, "def": 88, "spa": 140, "spd": 70, "spe": 112},
        "bst": 625,
    },
    {
        "pokemon_id": 460, "pokemon": "Abomasnow",
        "mega_name_en": "Mega Abomasnow", "mega_name_it": "Mega Abomasnow",
        "type1": "Grass", "type2": "Ice",
        "type1_it": "Erba", "type2_it": "Ghiaccio",
        "ability": "Snow Warning", "ability_it": "Scendineve",
        "mega_stone": "Abomasite", "mega_stone_it": "Abomasite",
        "stats": {"hp": 90, "atk": 132, "def": 105, "spa": 132, "spd": 105, "spe": 30},
        "bst": 594,
    },
    {
        "pokemon_id": 475, "pokemon": "Gallade",
        "mega_name_en": "Mega Gallade", "mega_name_it": "Mega Gallade",
        "type1": "Psychic", "type2": "Fighting",
        "type1_it": "Psico", "type2_it": "Lotta",
        "ability": "Inner Focus", "ability_it": "Forza Interiore",
        "mega_stone": "Galladite", "mega_stone_it": "Galladite",
        "stats": {"hp": 68, "atk": 165, "def": 95, "spa": 65, "spd": 115, "spe": 110},
        "bst": 618,
    },
    # --- Gen 5 Pokemon ---
    {
        "pokemon_id": 531, "pokemon": "Audino",
        "mega_name_en": "Mega Audino", "mega_name_it": "Mega Audino",
        "type1": "Normal", "type2": "Fairy",
        "type1_it": "Normale", "type2_it": "Folletto",
        "ability": "Healer", "ability_it": "Curacuore",
        "mega_stone": "Audinite", "mega_stone_it": "Audinite",
        "stats": {"hp": 103, "atk": 60, "def": 126, "spa": 80, "spd": 126, "spe": 50},
        "bst": 545,
    },
    # --- Gen 6 Pokemon ---
    {
        "pokemon_id": 719, "pokemon": "Diancie",
        "mega_name_en": "Mega Diancie", "mega_name_it": "Mega Diancie",
        "type1": "Rock", "type2": "Fairy",
        "type1_it": "Roccia", "type2_it": "Folletto",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Diancite", "mega_stone_it": "Diancite",
        "stats": {"hp": 50, "atk": 160, "def": 110, "spa": 160, "spd": 110, "spe": 110},
        "bst": 700,
    },
]
