"""Static data for all Mega Evolutions — classic (Gen 6-7) and new (Leggende Z-A).

Classic megas: 50 entries (46 species + Charizard X/Y, Mewtwo X/Y,
               Primal Kyogre/Groudon, Mega Rayquaza).
Z-A base game: 26 new megas.
Z-A Mega Dimension DLC: 22 entries (incl. Raichu X/Y, Magearna Original,
               Tatsugiri 3 forme, 3 Z-Mega: Absol Z/Garchomp Z/Lucario Z).
Grand total: 98 entries (some Pokemon have multiple mega forms).

Used by transformers.build_mega_evolution_documents() to generate:
- A summary doc listing all megas (for "quante mega evoluzioni esistono?")
- Per-Pokemon docs with full details (for "parlami di Mega Charizard X")

Data sourced from Bulbapedia / Serebii. Stats are post-mega transformation.
Z-A megas have za_exclusive=True and no abilities (Z-A uses passive effects instead).
Z-Mega evoluzioni (z_mega=True) hanno mosse senza caricamento ma consumano
Mega Power piu' in fretta.
"""

MEGA_EVOLUTIONS: list[dict] = [
    # =====================================================================
    #  CLASSIC MEGA EVOLUTIONS (Gen 6-7) — 50 entries
    # =====================================================================

    # --- Gen 1 Pokemon ---
    {
        "pokemon_id": 3, "pokemon": "Venusaur",
        "mega_name_en": "Mega Venusaur", "mega_name_it": "Mega Venusaur",
        "type1": "Grass", "type2": "Poison",
        "type1_it": "Erba", "type2_it": "Veleno",
        "ability": "Thick Fat", "ability_it": "Grassospesso",
        "mega_stone": "Venusaurite", "mega_stone_it": "Venusaurite",
        "stats": {"hp": 80, "atk": 100, "def": 123, "spa": 122, "spd": 120, "spe": 80},
        "bst": 625,
    },
    {
        "pokemon_id": 6, "pokemon": "Charizard",
        "mega_name_en": "Mega Charizard X", "mega_name_it": "Mega Charizard X",
        "type1": "Fire", "type2": "Dragon",
        "type1_it": "Fuoco", "type2_it": "Drago",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Charizardite X", "mega_stone_it": "Charizardite X",
        "stats": {"hp": 78, "atk": 130, "def": 111, "spa": 130, "spd": 85, "spe": 100},
        "bst": 634,
    },
    {
        "pokemon_id": 6, "pokemon": "Charizard",
        "mega_name_en": "Mega Charizard Y", "mega_name_it": "Mega Charizard Y",
        "type1": "Fire", "type2": "Flying",
        "type1_it": "Fuoco", "type2_it": "Volante",
        "ability": "Drought", "ability_it": "Siccita",
        "mega_stone": "Charizardite Y", "mega_stone_it": "Charizardite Y",
        "stats": {"hp": 78, "atk": 104, "def": 78, "spa": 159, "spd": 115, "spe": 100},
        "bst": 634,
    },
    {
        "pokemon_id": 9, "pokemon": "Blastoise",
        "mega_name_en": "Mega Blastoise", "mega_name_it": "Mega Blastoise",
        "type1": "Water", "type2": "",
        "type1_it": "Acqua", "type2_it": "",
        "ability": "Mega Launcher", "ability_it": "Megalancio",
        "mega_stone": "Blastoisinite", "mega_stone_it": "Blastoisinite",
        "stats": {"hp": 79, "atk": 103, "def": 120, "spa": 135, "spd": 115, "spe": 78},
        "bst": 630,
    },
    {
        "pokemon_id": 15, "pokemon": "Beedrill",
        "mega_name_en": "Mega Beedrill", "mega_name_it": "Mega Beedrill",
        "type1": "Bug", "type2": "Poison",
        "type1_it": "Coleottero", "type2_it": "Veleno",
        "ability": "Adaptability", "ability_it": "Adattabilita",
        "mega_stone": "Beedrillite", "mega_stone_it": "Beedrillite",
        "stats": {"hp": 65, "atk": 150, "def": 40, "spa": 15, "spd": 80, "spe": 145},
        "bst": 495,
    },
    {
        "pokemon_id": 18, "pokemon": "Pidgeot",
        "mega_name_en": "Mega Pidgeot", "mega_name_it": "Mega Pidgeot",
        "type1": "Normal", "type2": "Flying",
        "type1_it": "Normale", "type2_it": "Volante",
        "ability": "No Guard", "ability_it": "Nullaguardia",
        "mega_stone": "Pidgeotite", "mega_stone_it": "Pidgeotite",
        "stats": {"hp": 83, "atk": 80, "def": 80, "spa": 135, "spd": 80, "spe": 121},
        "bst": 579,
    },
    {
        "pokemon_id": 65, "pokemon": "Alakazam",
        "mega_name_en": "Mega Alakazam", "mega_name_it": "Mega Alakazam",
        "type1": "Psychic", "type2": "",
        "type1_it": "Psico", "type2_it": "",
        "ability": "Trace", "ability_it": "Traccia",
        "mega_stone": "Alakazite", "mega_stone_it": "Alakazamite",
        "stats": {"hp": 55, "atk": 50, "def": 65, "spa": 175, "spd": 105, "spe": 150},
        "bst": 600,
    },
    {
        "pokemon_id": 80, "pokemon": "Slowbro",
        "mega_name_en": "Mega Slowbro", "mega_name_it": "Mega Slowbro",
        "type1": "Water", "type2": "Psychic",
        "type1_it": "Acqua", "type2_it": "Psico",
        "ability": "Shell Armor", "ability_it": "Guscioscudo",
        "mega_stone": "Slowbronite", "mega_stone_it": "Slowbronite",
        "stats": {"hp": 95, "atk": 75, "def": 180, "spa": 130, "spd": 80, "spe": 30},
        "bst": 590,
    },
    {
        "pokemon_id": 94, "pokemon": "Gengar",
        "mega_name_en": "Mega Gengar", "mega_name_it": "Mega Gengar",
        "type1": "Ghost", "type2": "Poison",
        "type1_it": "Spettro", "type2_it": "Veleno",
        "ability": "Shadow Tag", "ability_it": "Pedinombra",
        "mega_stone": "Gengarite", "mega_stone_it": "Gengarite",
        "stats": {"hp": 60, "atk": 65, "def": 80, "spa": 170, "spd": 95, "spe": 130},
        "bst": 600,
    },
    {
        "pokemon_id": 115, "pokemon": "Kangaskhan",
        "mega_name_en": "Mega Kangaskhan", "mega_name_it": "Mega Kangaskhan",
        "type1": "Normal", "type2": "",
        "type1_it": "Normale", "type2_it": "",
        "ability": "Parental Bond", "ability_it": "Amorefiliale",
        "mega_stone": "Kangaskhanite", "mega_stone_it": "Kangaskhanite",
        "stats": {"hp": 105, "atk": 125, "def": 100, "spa": 60, "spd": 100, "spe": 100},
        "bst": 590,
    },
    {
        "pokemon_id": 127, "pokemon": "Pinsir",
        "mega_name_en": "Mega Pinsir", "mega_name_it": "Mega Pinsir",
        "type1": "Bug", "type2": "Flying",
        "type1_it": "Coleottero", "type2_it": "Volante",
        "ability": "Aerilate", "ability_it": "Aerificazione",
        "mega_stone": "Pinsirite", "mega_stone_it": "Pinsirite",
        "stats": {"hp": 65, "atk": 155, "def": 120, "spa": 65, "spd": 90, "spe": 105},
        "bst": 600,
    },
    {
        "pokemon_id": 130, "pokemon": "Gyarados",
        "mega_name_en": "Mega Gyarados", "mega_name_it": "Mega Gyarados",
        "type1": "Water", "type2": "Dark",
        "type1_it": "Acqua", "type2_it": "Buio",
        "ability": "Mold Breaker", "ability_it": "Rompiforma",
        "mega_stone": "Gyaradosite", "mega_stone_it": "Gyaradosite",
        "stats": {"hp": 95, "atk": 155, "def": 109, "spa": 70, "spd": 130, "spe": 81},
        "bst": 640,
    },
    {
        "pokemon_id": 142, "pokemon": "Aerodactyl",
        "mega_name_en": "Mega Aerodactyl", "mega_name_it": "Mega Aerodactyl",
        "type1": "Rock", "type2": "Flying",
        "type1_it": "Roccia", "type2_it": "Volante",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Aerodactylite", "mega_stone_it": "Aerodactylite",
        "stats": {"hp": 80, "atk": 135, "def": 85, "spa": 70, "spd": 95, "spe": 150},
        "bst": 615,
    },
    {
        "pokemon_id": 150, "pokemon": "Mewtwo",
        "mega_name_en": "Mega Mewtwo X", "mega_name_it": "Mega Mewtwo X",
        "type1": "Psychic", "type2": "Fighting",
        "type1_it": "Psico", "type2_it": "Lotta",
        "ability": "Steadfast", "ability_it": "Cuordeciso",
        "mega_stone": "Mewtwonite X", "mega_stone_it": "Mewtwonite X",
        "stats": {"hp": 106, "atk": 190, "def": 100, "spa": 154, "spd": 100, "spe": 130},
        "bst": 780,
    },
    {
        "pokemon_id": 150, "pokemon": "Mewtwo",
        "mega_name_en": "Mega Mewtwo Y", "mega_name_it": "Mega Mewtwo Y",
        "type1": "Psychic", "type2": "",
        "type1_it": "Psico", "type2_it": "",
        "ability": "Insomnia", "ability_it": "Insonnia",
        "mega_stone": "Mewtwonite Y", "mega_stone_it": "Mewtwonite Y",
        "stats": {"hp": 106, "atk": 150, "def": 70, "spa": 194, "spd": 120, "spe": 140},
        "bst": 780,
    },
    # --- Gen 2 Pokemon ---
    {
        "pokemon_id": 181, "pokemon": "Ampharos",
        "mega_name_en": "Mega Ampharos", "mega_name_it": "Mega Ampharos",
        "type1": "Electric", "type2": "Dragon",
        "type1_it": "Elettro", "type2_it": "Drago",
        "ability": "Mold Breaker", "ability_it": "Rompiforma",
        "mega_stone": "Ampharosite", "mega_stone_it": "Ampharosite",
        "stats": {"hp": 90, "atk": 95, "def": 105, "spa": 165, "spd": 110, "spe": 45},
        "bst": 610,
    },
    {
        "pokemon_id": 208, "pokemon": "Steelix",
        "mega_name_en": "Mega Steelix", "mega_name_it": "Mega Steelix",
        "type1": "Steel", "type2": "Ground",
        "type1_it": "Acciaio", "type2_it": "Terra",
        "ability": "Sand Force", "ability_it": "Sabbiaforza",
        "mega_stone": "Steelixite", "mega_stone_it": "Steelixite",
        "stats": {"hp": 75, "atk": 125, "def": 230, "spa": 55, "spd": 95, "spe": 30},
        "bst": 610,
    },
    {
        "pokemon_id": 212, "pokemon": "Scizor",
        "mega_name_en": "Mega Scizor", "mega_name_it": "Mega Scizor",
        "type1": "Bug", "type2": "Steel",
        "type1_it": "Coleottero", "type2_it": "Acciaio",
        "ability": "Technician", "ability_it": "Tecnico",
        "mega_stone": "Scizorite", "mega_stone_it": "Scizorite",
        "stats": {"hp": 70, "atk": 150, "def": 140, "spa": 65, "spd": 100, "spe": 75},
        "bst": 600,
    },
    {
        "pokemon_id": 214, "pokemon": "Heracross",
        "mega_name_en": "Mega Heracross", "mega_name_it": "Mega Heracross",
        "type1": "Bug", "type2": "Fighting",
        "type1_it": "Coleottero", "type2_it": "Lotta",
        "ability": "Skill Link", "ability_it": "Abillegame",
        "mega_stone": "Heracronite", "mega_stone_it": "Heracrossite",
        "stats": {"hp": 80, "atk": 185, "def": 115, "spa": 40, "spd": 105, "spe": 75},
        "bst": 600,
    },
    {
        "pokemon_id": 229, "pokemon": "Houndoom",
        "mega_name_en": "Mega Houndoom", "mega_name_it": "Mega Houndoom",
        "type1": "Dark", "type2": "Fire",
        "type1_it": "Buio", "type2_it": "Fuoco",
        "ability": "Solar Power", "ability_it": "Solarpotere",
        "mega_stone": "Houndoominite", "mega_stone_it": "Houndoomite",
        "stats": {"hp": 75, "atk": 90, "def": 90, "spa": 140, "spd": 90, "spe": 115},
        "bst": 600,
    },
    {
        "pokemon_id": 248, "pokemon": "Tyranitar",
        "mega_name_en": "Mega Tyranitar", "mega_name_it": "Mega Tyranitar",
        "type1": "Rock", "type2": "Dark",
        "type1_it": "Roccia", "type2_it": "Buio",
        "ability": "Sand Stream", "ability_it": "Sabbiafiume",
        "mega_stone": "Tyranitarite", "mega_stone_it": "Tyranitarite",
        "stats": {"hp": 100, "atk": 164, "def": 150, "spa": 95, "spd": 120, "spe": 71},
        "bst": 700,
    },
    # --- Gen 3 Pokemon ---
    {
        "pokemon_id": 254, "pokemon": "Sceptile",
        "mega_name_en": "Mega Sceptile", "mega_name_it": "Mega Sceptile",
        "type1": "Grass", "type2": "Dragon",
        "type1_it": "Erba", "type2_it": "Drago",
        "ability": "Lightning Rod", "ability_it": "Parafulmine",
        "mega_stone": "Sceptilite", "mega_stone_it": "Sceptilite",
        "stats": {"hp": 70, "atk": 110, "def": 75, "spa": 145, "spd": 85, "spe": 145},
        "bst": 630,
    },
    {
        "pokemon_id": 257, "pokemon": "Blaziken",
        "mega_name_en": "Mega Blaziken", "mega_name_it": "Mega Blaziken",
        "type1": "Fire", "type2": "Fighting",
        "type1_it": "Fuoco", "type2_it": "Lotta",
        "ability": "Speed Boost", "ability_it": "Velocita",
        "mega_stone": "Blazikenite", "mega_stone_it": "Blazikenite",
        "stats": {"hp": 80, "atk": 160, "def": 80, "spa": 130, "spd": 80, "spe": 100},
        "bst": 630,
    },
    {
        "pokemon_id": 260, "pokemon": "Swampert",
        "mega_name_en": "Mega Swampert", "mega_name_it": "Mega Swampert",
        "type1": "Water", "type2": "Ground",
        "type1_it": "Acqua", "type2_it": "Terra",
        "ability": "Swift Swim", "ability_it": "Nuotovelox",
        "mega_stone": "Swampertite", "mega_stone_it": "Swampertite",
        "stats": {"hp": 100, "atk": 150, "def": 110, "spa": 95, "spd": 110, "spe": 70},
        "bst": 635,
    },
    {
        "pokemon_id": 282, "pokemon": "Gardevoir",
        "mega_name_en": "Mega Gardevoir", "mega_name_it": "Mega Gardevoir",
        "type1": "Psychic", "type2": "Fairy",
        "type1_it": "Psico", "type2_it": "Folletto",
        "ability": "Pixilate", "ability_it": "Pellefolletto",
        "mega_stone": "Gardevoirite", "mega_stone_it": "Gardevoirite",
        "stats": {"hp": 68, "atk": 85, "def": 65, "spa": 165, "spd": 135, "spe": 100},
        "bst": 618,
    },
    {
        "pokemon_id": 302, "pokemon": "Sableye",
        "mega_name_en": "Mega Sableye", "mega_name_it": "Mega Sableye",
        "type1": "Dark", "type2": "Ghost",
        "type1_it": "Buio", "type2_it": "Spettro",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Sablenite", "mega_stone_it": "Sableyite",
        "stats": {"hp": 50, "atk": 85, "def": 125, "spa": 85, "spd": 115, "spe": 20},
        "bst": 480,
    },
    {
        "pokemon_id": 303, "pokemon": "Mawile",
        "mega_name_en": "Mega Mawile", "mega_name_it": "Mega Mawile",
        "type1": "Steel", "type2": "Fairy",
        "type1_it": "Acciaio", "type2_it": "Folletto",
        "ability": "Huge Power", "ability_it": "Macroforza",
        "mega_stone": "Mawilite", "mega_stone_it": "Mawilite",
        "stats": {"hp": 50, "atk": 105, "def": 125, "spa": 55, "spd": 95, "spe": 50},
        "bst": 480,
    },
    {
        "pokemon_id": 306, "pokemon": "Aggron",
        "mega_name_en": "Mega Aggron", "mega_name_it": "Mega Aggron",
        "type1": "Steel", "type2": "",
        "type1_it": "Acciaio", "type2_it": "",
        "ability": "Filter", "ability_it": "Filtro",
        "mega_stone": "Aggronite", "mega_stone_it": "Aggronite",
        "stats": {"hp": 70, "atk": 140, "def": 230, "spa": 60, "spd": 80, "spe": 50},
        "bst": 630,
    },
    {
        "pokemon_id": 308, "pokemon": "Medicham",
        "mega_name_en": "Mega Medicham", "mega_name_it": "Mega Medicham",
        "type1": "Fighting", "type2": "Psychic",
        "type1_it": "Lotta", "type2_it": "Psico",
        "ability": "Pure Power", "ability_it": "Forzapura",
        "mega_stone": "Medichamite", "mega_stone_it": "Medichamite",
        "stats": {"hp": 60, "atk": 100, "def": 85, "spa": 80, "spd": 85, "spe": 100},
        "bst": 510,
    },
    {
        "pokemon_id": 310, "pokemon": "Manectric",
        "mega_name_en": "Mega Manectric", "mega_name_it": "Mega Manectric",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "Intimidate", "ability_it": "Prepotenza",
        "mega_stone": "Manectite", "mega_stone_it": "Manectricite",
        "stats": {"hp": 70, "atk": 75, "def": 80, "spa": 135, "spd": 80, "spe": 135},
        "bst": 575,
    },
    {
        "pokemon_id": 319, "pokemon": "Sharpedo",
        "mega_name_en": "Mega Sharpedo", "mega_name_it": "Mega Sharpedo",
        "type1": "Water", "type2": "Dark",
        "type1_it": "Acqua", "type2_it": "Buio",
        "ability": "Strong Jaw", "ability_it": "Ferromascella",
        "mega_stone": "Sharpedonite", "mega_stone_it": "Sharpedonite",
        "stats": {"hp": 70, "atk": 140, "def": 70, "spa": 110, "spd": 65, "spe": 105},
        "bst": 560,
    },
    {
        "pokemon_id": 323, "pokemon": "Camerupt",
        "mega_name_en": "Mega Camerupt", "mega_name_it": "Mega Camerupt",
        "type1": "Fire", "type2": "Ground",
        "type1_it": "Fuoco", "type2_it": "Terra",
        "ability": "Sheer Force", "ability_it": "Forzabruta",
        "mega_stone": "Cameruptite", "mega_stone_it": "Cameruptite",
        "stats": {"hp": 70, "atk": 120, "def": 100, "spa": 145, "spd": 105, "spe": 20},
        "bst": 560,
    },
    {
        "pokemon_id": 334, "pokemon": "Altaria",
        "mega_name_en": "Mega Altaria", "mega_name_it": "Mega Altaria",
        "type1": "Dragon", "type2": "Fairy",
        "type1_it": "Drago", "type2_it": "Folletto",
        "ability": "Pixilate", "ability_it": "Pellefolletto",
        "mega_stone": "Altarianite", "mega_stone_it": "Altarianite",
        "stats": {"hp": 75, "atk": 110, "def": 110, "spa": 110, "spd": 105, "spe": 80},
        "bst": 590,
    },
    {
        "pokemon_id": 354, "pokemon": "Banette",
        "mega_name_en": "Mega Banette", "mega_name_it": "Mega Banette",
        "type1": "Ghost", "type2": "",
        "type1_it": "Spettro", "type2_it": "",
        "ability": "Prankster", "ability_it": "Burla",
        "mega_stone": "Banettite", "mega_stone_it": "Banettite",
        "stats": {"hp": 64, "atk": 165, "def": 75, "spa": 93, "spd": 83, "spe": 75},
        "bst": 555,
    },
    {
        "pokemon_id": 359, "pokemon": "Absol",
        "mega_name_en": "Mega Absol", "mega_name_it": "Mega Absol",
        "type1": "Dark", "type2": "",
        "type1_it": "Buio", "type2_it": "",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Absolite", "mega_stone_it": "Absolite",
        "stats": {"hp": 65, "atk": 150, "def": 60, "spa": 115, "spd": 60, "spe": 115},
        "bst": 565,
    },
    {
        "pokemon_id": 362, "pokemon": "Glalie",
        "mega_name_en": "Mega Glalie", "mega_name_it": "Mega Glalie",
        "type1": "Ice", "type2": "",
        "type1_it": "Ghiaccio", "type2_it": "",
        "ability": "Refrigerate", "ability_it": "Pellegelo",
        "mega_stone": "Glalitite", "mega_stone_it": "Glalitite",
        "stats": {"hp": 80, "atk": 120, "def": 80, "spa": 120, "spd": 80, "spe": 100},
        "bst": 580,
    },
    {
        "pokemon_id": 373, "pokemon": "Salamence",
        "mega_name_en": "Mega Salamence", "mega_name_it": "Mega Salamence",
        "type1": "Dragon", "type2": "Flying",
        "type1_it": "Drago", "type2_it": "Volante",
        "ability": "Aerilate", "ability_it": "Aerificazione",
        "mega_stone": "Salamencite", "mega_stone_it": "Salamencite",
        "stats": {"hp": 95, "atk": 145, "def": 130, "spa": 120, "spd": 90, "spe": 120},
        "bst": 700,
    },
    {
        "pokemon_id": 376, "pokemon": "Metagross",
        "mega_name_en": "Mega Metagross", "mega_name_it": "Mega Metagross",
        "type1": "Steel", "type2": "Psychic",
        "type1_it": "Acciaio", "type2_it": "Psico",
        "ability": "Tough Claws", "ability_it": "Unghiedure",
        "mega_stone": "Metagrossite", "mega_stone_it": "Metagrossite",
        "stats": {"hp": 80, "atk": 145, "def": 150, "spa": 105, "spd": 110, "spe": 110},
        "bst": 700,
    },
    {
        "pokemon_id": 380, "pokemon": "Latias",
        "mega_name_en": "Mega Latias", "mega_name_it": "Mega Latias",
        "type1": "Dragon", "type2": "Psychic",
        "type1_it": "Drago", "type2_it": "Psico",
        "ability": "Levitate", "ability_it": "Levitazione",
        "mega_stone": "Latiasite", "mega_stone_it": "Latiasite",
        "stats": {"hp": 80, "atk": 100, "def": 120, "spa": 140, "spd": 150, "spe": 110},
        "bst": 700,
    },
    {
        "pokemon_id": 381, "pokemon": "Latios",
        "mega_name_en": "Mega Latios", "mega_name_it": "Mega Latios",
        "type1": "Dragon", "type2": "Psychic",
        "type1_it": "Drago", "type2_it": "Psico",
        "ability": "Levitate", "ability_it": "Levitazione",
        "mega_stone": "Latiosite", "mega_stone_it": "Latiosite",
        "stats": {"hp": 80, "atk": 130, "def": 100, "spa": 160, "spd": 120, "spe": 110},
        "bst": 700,
    },
    # --- Gen 3 Legendaries (Primal Reversion, counted as Mega for gameplay) ---
    {
        "pokemon_id": 382, "pokemon": "Kyogre",
        "mega_name_en": "Primal Kyogre", "mega_name_it": "Kyogre Ancestrale",
        "type1": "Water", "type2": "",
        "type1_it": "Acqua", "type2_it": "",
        "ability": "Primordial Sea", "ability_it": "Mare Primordiale",
        "mega_stone": "Blue Orb", "mega_stone_it": "Gemma Blu",
        "stats": {"hp": 100, "atk": 150, "def": 90, "spa": 180, "spd": 160, "spe": 90},
        "bst": 770,
    },
    {
        "pokemon_id": 383, "pokemon": "Groudon",
        "mega_name_en": "Primal Groudon", "mega_name_it": "Groudon Ancestrale",
        "type1": "Ground", "type2": "Fire",
        "type1_it": "Terra", "type2_it": "Fuoco",
        "ability": "Desolate Land", "ability_it": "Terra Estrema",
        "mega_stone": "Red Orb", "mega_stone_it": "Gemma Rossa",
        "stats": {"hp": 100, "atk": 180, "def": 160, "spa": 150, "spd": 90, "spe": 90},
        "bst": 770,
    },
    {
        "pokemon_id": 384, "pokemon": "Rayquaza",
        "mega_name_en": "Mega Rayquaza", "mega_name_it": "Mega Rayquaza",
        "type1": "Dragon", "type2": "Flying",
        "type1_it": "Drago", "type2_it": "Volante",
        "ability": "Delta Stream", "ability_it": "Flusso Delta",
        "mega_stone": "Dragon Ascent (move)", "mega_stone_it": "Ascesa del Drago (mossa)",
        "stats": {"hp": 105, "atk": 180, "def": 100, "spa": 180, "spd": 100, "spe": 115},
        "bst": 780,
    },
    # --- Gen 4 Pokemon ---
    {
        "pokemon_id": 428, "pokemon": "Lopunny",
        "mega_name_en": "Mega Lopunny", "mega_name_it": "Mega Lopunny",
        "type1": "Normal", "type2": "Fighting",
        "type1_it": "Normale", "type2_it": "Lotta",
        "ability": "Scrappy", "ability_it": "Nerointento",
        "mega_stone": "Lopunnite", "mega_stone_it": "Lopunnite",
        "stats": {"hp": 65, "atk": 136, "def": 94, "spa": 54, "spd": 96, "spe": 135},
        "bst": 580,
    },
    {
        "pokemon_id": 445, "pokemon": "Garchomp",
        "mega_name_en": "Mega Garchomp", "mega_name_it": "Mega Garchomp",
        "type1": "Dragon", "type2": "Ground",
        "type1_it": "Drago", "type2_it": "Terra",
        "ability": "Sand Force", "ability_it": "Sabbiaforza",
        "mega_stone": "Garchompite", "mega_stone_it": "Garchompite",
        "stats": {"hp": 108, "atk": 170, "def": 115, "spa": 120, "spd": 95, "spe": 92},
        "bst": 700,
    },
    {
        "pokemon_id": 448, "pokemon": "Lucario",
        "mega_name_en": "Mega Lucario", "mega_name_it": "Mega Lucario",
        "type1": "Fighting", "type2": "Steel",
        "type1_it": "Lotta", "type2_it": "Acciaio",
        "ability": "Adaptability", "ability_it": "Adattabilita",
        "mega_stone": "Lucarionite", "mega_stone_it": "Lucarite",
        "stats": {"hp": 70, "atk": 145, "def": 88, "spa": 140, "spd": 70, "spe": 112},
        "bst": 625,
    },
    {
        "pokemon_id": 460, "pokemon": "Abomasnow",
        "mega_name_en": "Mega Abomasnow", "mega_name_it": "Mega Abomasnow",
        "type1": "Grass", "type2": "Ice",
        "type1_it": "Erba", "type2_it": "Ghiaccio",
        "ability": "Snow Warning", "ability_it": "Scendineve",
        "mega_stone": "Abomasite", "mega_stone_it": "Abomasite",
        "stats": {"hp": 90, "atk": 132, "def": 105, "spa": 132, "spd": 105, "spe": 30},
        "bst": 594,
    },
    {
        "pokemon_id": 475, "pokemon": "Gallade",
        "mega_name_en": "Mega Gallade", "mega_name_it": "Mega Gallade",
        "type1": "Psychic", "type2": "Fighting",
        "type1_it": "Psico", "type2_it": "Lotta",
        "ability": "Inner Focus", "ability_it": "Forza Interiore",
        "mega_stone": "Galladite", "mega_stone_it": "Galladite",
        "stats": {"hp": 68, "atk": 165, "def": 95, "spa": 65, "spd": 115, "spe": 110},
        "bst": 618,
    },
    # --- Gen 5 Pokemon ---
    {
        "pokemon_id": 531, "pokemon": "Audino",
        "mega_name_en": "Mega Audino", "mega_name_it": "Mega Audino",
        "type1": "Normal", "type2": "Fairy",
        "type1_it": "Normale", "type2_it": "Folletto",
        "ability": "Healer", "ability_it": "Curacuore",
        "mega_stone": "Audinite", "mega_stone_it": "Audinite",
        "stats": {"hp": 103, "atk": 60, "def": 126, "spa": 80, "spd": 126, "spe": 50},
        "bst": 545,
    },
    # --- Gen 6 Pokemon ---
    {
        "pokemon_id": 719, "pokemon": "Diancie",
        "mega_name_en": "Mega Diancie", "mega_name_it": "Mega Diancie",
        "type1": "Rock", "type2": "Fairy",
        "type1_it": "Roccia", "type2_it": "Folletto",
        "ability": "Magic Bounce", "ability_it": "Magispecchio",
        "mega_stone": "Diancite", "mega_stone_it": "Diancite",
        "stats": {"hp": 50, "atk": 160, "def": 110, "spa": 160, "spd": 110, "spe": 110},
        "bst": 700,
    },

    # =====================================================================
    #  LEGGENDE POKEMON Z-A — Nuove Mega Evoluzioni (base game, 26 entries)
    # =====================================================================
    #
    # Note: In Leggende Z-A le abilita' non esistono (sostituite da effetti
    # passivi). I campi ability/ability_it sono vuoti. za_exclusive=True.

    # --- Gen 1 Pokemon (Z-A) ---
    {
        "pokemon_id": 36, "pokemon": "Clefable",
        "mega_name_en": "Mega Clefable", "mega_name_it": "Mega Clefable",
        "type1": "Fairy", "type2": "Flying",
        "type1_it": "Folletto", "type2_it": "Volante",
        "ability": "", "ability_it": "",
        "mega_stone": "Clefablite", "mega_stone_it": "Clefablite",
        "stats": {"hp": 95, "atk": 80, "def": 93, "spa": 135, "spd": 110, "spe": 70},
        "bst": 583, "za_exclusive": True,
    },
    {
        "pokemon_id": 71, "pokemon": "Victreebel",
        "mega_name_en": "Mega Victreebel", "mega_name_it": "Mega Victreebel",
        "type1": "Grass", "type2": "Poison",
        "type1_it": "Erba", "type2_it": "Veleno",
        "ability": "", "ability_it": "",
        "mega_stone": "Victreebelite", "mega_stone_it": "Victreebelite",
        "stats": {"hp": 80, "atk": 125, "def": 85, "spa": 135, "spd": 95, "spe": 70},
        "bst": 590, "za_exclusive": True,
    },
    {
        "pokemon_id": 121, "pokemon": "Starmie",
        "mega_name_en": "Mega Starmie", "mega_name_it": "Mega Starmie",
        "type1": "Water", "type2": "Psychic",
        "type1_it": "Acqua", "type2_it": "Psico",
        "ability": "", "ability_it": "",
        "mega_stone": "Starmiite", "mega_stone_it": "Starmiite",
        "stats": {"hp": 60, "atk": 140, "def": 105, "spa": 130, "spd": 105, "spe": 120},
        "bst": 660, "za_exclusive": True,
    },
    {
        "pokemon_id": 149, "pokemon": "Dragonite",
        "mega_name_en": "Mega Dragonite", "mega_name_it": "Mega Dragonite",
        "type1": "Dragon", "type2": "Flying",
        "type1_it": "Drago", "type2_it": "Volante",
        "ability": "", "ability_it": "",
        "mega_stone": "Dragonitite", "mega_stone_it": "Dragonitite",
        "stats": {"hp": 91, "atk": 124, "def": 115, "spa": 145, "spd": 125, "spe": 100},
        "bst": 700, "za_exclusive": True,
    },
    # --- Gen 2 Pokemon (Z-A) ---
    {
        "pokemon_id": 154, "pokemon": "Meganium",
        "mega_name_en": "Mega Meganium", "mega_name_it": "Mega Meganium",
        "type1": "Grass", "type2": "Fairy",
        "type1_it": "Erba", "type2_it": "Folletto",
        "ability": "", "ability_it": "",
        "mega_stone": "Meganiumite", "mega_stone_it": "Meganiumite",
        "stats": {"hp": 80, "atk": 92, "def": 115, "spa": 143, "spd": 115, "spe": 80},
        "bst": 625, "za_exclusive": True,
    },
    {
        "pokemon_id": 160, "pokemon": "Feraligatr",
        "mega_name_en": "Mega Feraligatr", "mega_name_it": "Mega Feraligatr",
        "type1": "Water", "type2": "Dragon",
        "type1_it": "Acqua", "type2_it": "Drago",
        "ability": "", "ability_it": "",
        "mega_stone": "Feraligatrite", "mega_stone_it": "Feraligatrite",
        "stats": {"hp": 85, "atk": 160, "def": 125, "spa": 89, "spd": 93, "spe": 78},
        "bst": 630, "za_exclusive": True,
    },
    {
        "pokemon_id": 227, "pokemon": "Skarmory",
        "mega_name_en": "Mega Skarmory", "mega_name_it": "Mega Skarmory",
        "type1": "Steel", "type2": "Flying",
        "type1_it": "Acciaio", "type2_it": "Volante",
        "ability": "", "ability_it": "",
        "mega_stone": "Skarmoryite", "mega_stone_it": "Skarmoryite",
        "stats": {"hp": 65, "atk": 140, "def": 110, "spa": 40, "spd": 100, "spe": 110},
        "bst": 565, "za_exclusive": True,
    },
    # --- Gen 4 Pokemon (Z-A) ---
    {
        "pokemon_id": 478, "pokemon": "Froslass",
        "mega_name_en": "Mega Froslass", "mega_name_it": "Mega Froslass",
        "type1": "Ice", "type2": "Ghost",
        "type1_it": "Ghiaccio", "type2_it": "Spettro",
        "ability": "", "ability_it": "",
        "mega_stone": "Froslassite", "mega_stone_it": "Froslassite",
        "stats": {"hp": 70, "atk": 80, "def": 70, "spa": 140, "spd": 100, "spe": 120},
        "bst": 580, "za_exclusive": True,
    },
    # --- Gen 5 Pokemon (Z-A) ---
    {
        "pokemon_id": 500, "pokemon": "Emboar",
        "mega_name_en": "Mega Emboar", "mega_name_it": "Mega Emboar",
        "type1": "Fire", "type2": "Fighting",
        "type1_it": "Fuoco", "type2_it": "Lotta",
        "ability": "", "ability_it": "",
        "mega_stone": "Emboarite", "mega_stone_it": "Emboarite",
        "stats": {"hp": 110, "atk": 148, "def": 75, "spa": 110, "spd": 110, "spe": 75},
        "bst": 628, "za_exclusive": True,
    },
    {
        "pokemon_id": 530, "pokemon": "Excadrill",
        "mega_name_en": "Mega Excadrill", "mega_name_it": "Mega Excadrill",
        "type1": "Ground", "type2": "Steel",
        "type1_it": "Terra", "type2_it": "Acciaio",
        "ability": "", "ability_it": "",
        "mega_stone": "Excadrillite", "mega_stone_it": "Excadrillite",
        "stats": {"hp": 110, "atk": 165, "def": 100, "spa": 65, "spd": 65, "spe": 103},
        "bst": 608, "za_exclusive": True,
    },
    {
        "pokemon_id": 545, "pokemon": "Scolipede",
        "mega_name_en": "Mega Scolipede", "mega_name_it": "Mega Scolipede",
        "type1": "Bug", "type2": "Poison",
        "type1_it": "Coleottero", "type2_it": "Veleno",
        "ability": "", "ability_it": "",
        "mega_stone": "Scolipedite", "mega_stone_it": "Scolipedite",
        "stats": {"hp": 60, "atk": 140, "def": 149, "spa": 75, "spd": 99, "spe": 62},
        "bst": 585, "za_exclusive": True,
    },
    {
        "pokemon_id": 560, "pokemon": "Scrafty",
        "mega_name_en": "Mega Scrafty", "mega_name_it": "Mega Scrafty",
        "type1": "Dark", "type2": "Fighting",
        "type1_it": "Buio", "type2_it": "Lotta",
        "ability": "", "ability_it": "",
        "mega_stone": "Scraftite", "mega_stone_it": "Scraftite",
        "stats": {"hp": 65, "atk": 130, "def": 135, "spa": 55, "spd": 135, "spe": 68},
        "bst": 588, "za_exclusive": True,
    },
    {
        "pokemon_id": 604, "pokemon": "Eelektross",
        "mega_name_en": "Mega Eelektross", "mega_name_it": "Mega Eelektross",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Eelektrossite", "mega_stone_it": "Eelektrossite",
        "stats": {"hp": 85, "atk": 145, "def": 80, "spa": 135, "spd": 90, "spe": 80},
        "bst": 615, "za_exclusive": True,
    },
    {
        "pokemon_id": 609, "pokemon": "Chandelure",
        "mega_name_en": "Mega Chandelure", "mega_name_it": "Mega Chandelure",
        "type1": "Ghost", "type2": "Fire",
        "type1_it": "Spettro", "type2_it": "Fuoco",
        "ability": "", "ability_it": "",
        "mega_stone": "Chandelurite", "mega_stone_it": "Chandelurite",
        "stats": {"hp": 60, "atk": 75, "def": 110, "spa": 175, "spd": 110, "spe": 90},
        "bst": 620, "za_exclusive": True,
    },
    # --- Gen 6 Pokemon (Z-A) ---
    {
        "pokemon_id": 652, "pokemon": "Chesnaught",
        "mega_name_en": "Mega Chesnaught", "mega_name_it": "Mega Chesnaught",
        "type1": "Grass", "type2": "Fighting",
        "type1_it": "Erba", "type2_it": "Lotta",
        "ability": "", "ability_it": "",
        "mega_stone": "Chesnaughtite", "mega_stone_it": "Chesnaughtite",
        "stats": {"hp": 88, "atk": 137, "def": 172, "spa": 74, "spd": 115, "spe": 44},
        "bst": 630, "za_exclusive": True,
    },
    {
        "pokemon_id": 655, "pokemon": "Delphox",
        "mega_name_en": "Mega Delphox", "mega_name_it": "Mega Delphox",
        "type1": "Fire", "type2": "Psychic",
        "type1_it": "Fuoco", "type2_it": "Psico",
        "ability": "", "ability_it": "",
        "mega_stone": "Delphoxite", "mega_stone_it": "Delphoxite",
        "stats": {"hp": 75, "atk": 69, "def": 72, "spa": 159, "spd": 125, "spe": 134},
        "bst": 634, "za_exclusive": True,
    },
    {
        "pokemon_id": 658, "pokemon": "Greninja",
        "mega_name_en": "Mega Greninja", "mega_name_it": "Mega Greninja",
        "type1": "Water", "type2": "Dark",
        "type1_it": "Acqua", "type2_it": "Buio",
        "ability": "", "ability_it": "",
        "mega_stone": "Greninjite", "mega_stone_it": "Greninjite",
        "stats": {"hp": 72, "atk": 125, "def": 77, "spa": 133, "spd": 81, "spe": 142},
        "bst": 630, "za_exclusive": True,
    },
    {
        "pokemon_id": 668, "pokemon": "Pyroar",
        "mega_name_en": "Mega Pyroar", "mega_name_it": "Mega Pyroar",
        "type1": "Fire", "type2": "Normal",
        "type1_it": "Fuoco", "type2_it": "Normale",
        "ability": "", "ability_it": "",
        "mega_stone": "Pyroarite", "mega_stone_it": "Pyroarite",
        "stats": {"hp": 86, "atk": 88, "def": 92, "spa": 129, "spd": 86, "spe": 126},
        "bst": 607, "za_exclusive": True,
    },
    {
        "pokemon_id": 670, "pokemon": "Floette",
        "mega_name_en": "Mega Floette", "mega_name_it": "Mega Floette",
        "type1": "Fairy", "type2": "",
        "type1_it": "Folletto", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Floettite", "mega_stone_it": "Floettite",
        "stats": {"hp": 74, "atk": 85, "def": 87, "spa": 155, "spd": 148, "spe": 102},
        "bst": 651, "za_exclusive": True,
    },
    {
        "pokemon_id": 687, "pokemon": "Malamar",
        "mega_name_en": "Mega Malamar", "mega_name_it": "Mega Malamar",
        "type1": "Dark", "type2": "Psychic",
        "type1_it": "Buio", "type2_it": "Psico",
        "ability": "", "ability_it": "",
        "mega_stone": "Malamarite", "mega_stone_it": "Malamarite",
        "stats": {"hp": 86, "atk": 102, "def": 88, "spa": 98, "spd": 120, "spe": 88},
        "bst": 582, "za_exclusive": True,
    },
    {
        "pokemon_id": 689, "pokemon": "Barbaracle",
        "mega_name_en": "Mega Barbaracle", "mega_name_it": "Mega Barbaracle",
        "type1": "Rock", "type2": "Fighting",
        "type1_it": "Roccia", "type2_it": "Lotta",
        "ability": "", "ability_it": "",
        "mega_stone": "Barbaraclite", "mega_stone_it": "Barbaraclite",
        "stats": {"hp": 72, "atk": 140, "def": 130, "spa": 64, "spd": 106, "spe": 88},
        "bst": 600, "za_exclusive": True,
    },
    {
        "pokemon_id": 691, "pokemon": "Dragalge",
        "mega_name_en": "Mega Dragalge", "mega_name_it": "Mega Dragalge",
        "type1": "Poison", "type2": "Dragon",
        "type1_it": "Veleno", "type2_it": "Drago",
        "ability": "", "ability_it": "",
        "mega_stone": "Dragalgite", "mega_stone_it": "Dragalgite",
        "stats": {"hp": 65, "atk": 85, "def": 105, "spa": 132, "spd": 163, "spe": 44},
        "bst": 594, "za_exclusive": True,
    },
    {
        "pokemon_id": 701, "pokemon": "Hawlucha",
        "mega_name_en": "Mega Hawlucha", "mega_name_it": "Mega Hawlucha",
        "type1": "Fighting", "type2": "Flying",
        "type1_it": "Lotta", "type2_it": "Volante",
        "ability": "", "ability_it": "",
        "mega_stone": "Hawluchite", "mega_stone_it": "Hawluchite",
        "stats": {"hp": 78, "atk": 137, "def": 100, "spa": 74, "spd": 93, "spe": 118},
        "bst": 600, "za_exclusive": True,
    },
    {
        "pokemon_id": 718, "pokemon": "Zygarde",
        "mega_name_en": "Mega Zygarde", "mega_name_it": "Mega Zygarde",
        "type1": "Dragon", "type2": "Ground",
        "type1_it": "Drago", "type2_it": "Terra",
        "ability": "", "ability_it": "",
        "mega_stone": "Zygardite", "mega_stone_it": "Zygardite",
        "stats": {"hp": 216, "atk": 70, "def": 91, "spa": 216, "spd": 85, "spe": 100},
        "bst": 778, "za_exclusive": True,
    },
    # --- Gen 7 Pokemon (Z-A) ---
    {
        "pokemon_id": 780, "pokemon": "Drampa",
        "mega_name_en": "Mega Drampa", "mega_name_it": "Mega Drampa",
        "type1": "Normal", "type2": "Dragon",
        "type1_it": "Normale", "type2_it": "Drago",
        "ability": "", "ability_it": "",
        "mega_stone": "Drampite", "mega_stone_it": "Drampite",
        "stats": {"hp": 78, "atk": 85, "def": 110, "spa": 160, "spd": 116, "spe": 36},
        "bst": 585, "za_exclusive": True,
    },
    # --- Gen 8 Pokemon (Z-A) ---
    {
        "pokemon_id": 870, "pokemon": "Falinks",
        "mega_name_en": "Mega Falinks", "mega_name_it": "Mega Falinks",
        "type1": "Fighting", "type2": "",
        "type1_it": "Lotta", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Falinksite", "mega_stone_it": "Falinksite",
        "stats": {"hp": 65, "atk": 135, "def": 135, "spa": 70, "spd": 65, "spe": 100},
        "bst": 570, "za_exclusive": True,
    },

    # =====================================================================
    #  LEGGENDE POKEMON Z-A: MEGA DIMENSION DLC — 22 entries
    # =====================================================================
    #
    # Include 3 "Z Mega Evoluzioni" (Absol Z, Garchomp Z, Lucario Z)
    # che hanno mosse senza caricamento ma consumano Mega Power piu' in fretta.

    # --- Gen 1 Pokemon (DLC) ---
    {
        "pokemon_id": 26, "pokemon": "Raichu",
        "mega_name_en": "Mega Raichu X", "mega_name_it": "Mega Raichu X",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Raichunite X", "mega_stone_it": "Raichunite X",
        "stats": {"hp": 60, "atk": 135, "def": 95, "spa": 90, "spd": 95, "spe": 110},
        "bst": 585, "za_exclusive": True,
    },
    {
        "pokemon_id": 26, "pokemon": "Raichu",
        "mega_name_en": "Mega Raichu Y", "mega_name_it": "Mega Raichu Y",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Raichunite Y", "mega_stone_it": "Raichunite Y",
        "stats": {"hp": 60, "atk": 100, "def": 55, "spa": 160, "spd": 80, "spe": 130},
        "bst": 585, "za_exclusive": True,
    },
    # --- Gen 3 Pokemon (DLC) ---
    {
        "pokemon_id": 358, "pokemon": "Chimecho",
        "mega_name_en": "Mega Chimecho", "mega_name_it": "Mega Chimecho",
        "type1": "Psychic", "type2": "Steel",
        "type1_it": "Psico", "type2_it": "Acciaio",
        "ability": "", "ability_it": "",
        "mega_stone": "Chimechite", "mega_stone_it": "Chimechite",
        "stats": {"hp": 75, "atk": 50, "def": 110, "spa": 135, "spd": 120, "spe": 65},
        "bst": 555, "za_exclusive": True,
    },
    {
        "pokemon_id": 359, "pokemon": "Absol",
        "mega_name_en": "Mega Absol Z", "mega_name_it": "Mega Absol Z",
        "type1": "Dark", "type2": "Ghost",
        "type1_it": "Buio", "type2_it": "Spettro",
        "ability": "", "ability_it": "",
        "mega_stone": "Absolite Z", "mega_stone_it": "Absolite Z",
        "stats": {"hp": 65, "atk": 154, "def": 60, "spa": 75, "spd": 60, "spe": 151},
        "bst": 565, "za_exclusive": True, "z_mega": True,
    },
    # --- Gen 4 Pokemon (DLC) ---
    {
        "pokemon_id": 398, "pokemon": "Staraptor",
        "mega_name_en": "Mega Staraptor", "mega_name_it": "Mega Staraptor",
        "type1": "Fighting", "type2": "Flying",
        "type1_it": "Lotta", "type2_it": "Volante",
        "ability": "", "ability_it": "",
        "mega_stone": "Staraptorite", "mega_stone_it": "Staraptorite",
        "stats": {"hp": 85, "atk": 140, "def": 100, "spa": 60, "spd": 90, "spe": 110},
        "bst": 585, "za_exclusive": True,
    },
    {
        "pokemon_id": 445, "pokemon": "Garchomp",
        "mega_name_en": "Mega Garchomp Z", "mega_name_it": "Mega Garchomp Z",
        "type1": "Dragon", "type2": "",
        "type1_it": "Drago", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Garchompite Z", "mega_stone_it": "Garchompite Z",
        "stats": {"hp": 108, "atk": 130, "def": 85, "spa": 141, "spd": 85, "spe": 151},
        "bst": 700, "za_exclusive": True, "z_mega": True,
    },
    {
        "pokemon_id": 448, "pokemon": "Lucario",
        "mega_name_en": "Mega Lucario Z", "mega_name_it": "Mega Lucario Z",
        "type1": "Fighting", "type2": "Steel",
        "type1_it": "Lotta", "type2_it": "Acciaio",
        "ability": "", "ability_it": "",
        "mega_stone": "Lucarite Z", "mega_stone_it": "Lucarite Z",
        "stats": {"hp": 70, "atk": 100, "def": 70, "spa": 164, "spd": 70, "spe": 151},
        "bst": 625, "za_exclusive": True, "z_mega": True,
    },
    {
        "pokemon_id": 485, "pokemon": "Heatran",
        "mega_name_en": "Mega Heatran", "mega_name_it": "Mega Heatran",
        "type1": "Fire", "type2": "Steel",
        "type1_it": "Fuoco", "type2_it": "Acciaio",
        "ability": "", "ability_it": "",
        "mega_stone": "Heatranite", "mega_stone_it": "Heatranite",
        "stats": {"hp": 91, "atk": 120, "def": 106, "spa": 175, "spd": 141, "spe": 67},
        "bst": 700, "za_exclusive": True,
    },
    {
        "pokemon_id": 491, "pokemon": "Darkrai",
        "mega_name_en": "Mega Darkrai", "mega_name_it": "Mega Darkrai",
        "type1": "Dark", "type2": "",
        "type1_it": "Buio", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Darkraite", "mega_stone_it": "Darkraite",
        "stats": {"hp": 70, "atk": 120, "def": 130, "spa": 165, "spd": 130, "spe": 85},
        "bst": 700, "za_exclusive": True,
    },
    # --- Gen 5 Pokemon (DLC) ---
    {
        "pokemon_id": 623, "pokemon": "Golurk",
        "mega_name_en": "Mega Golurk", "mega_name_it": "Mega Golurk",
        "type1": "Ground", "type2": "Ghost",
        "type1_it": "Terra", "type2_it": "Spettro",
        "ability": "", "ability_it": "",
        "mega_stone": "Golurkite", "mega_stone_it": "Golurkite",
        "stats": {"hp": 89, "atk": 159, "def": 105, "spa": 70, "spd": 105, "spe": 55},
        "bst": 583, "za_exclusive": True,
    },
    # --- Gen 5 Pokemon (DLC) ---  (cont.)
    # (Golurk is above)
    # --- Gen 6 Pokemon (DLC) ---
    {
        "pokemon_id": 678, "pokemon": "Meowstic",
        "mega_name_en": "Mega Meowstic", "mega_name_it": "Mega Meowstic",
        "type1": "Psychic", "type2": "",
        "type1_it": "Psico", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Meowsticite", "mega_stone_it": "Meowsticite",
        "stats": {"hp": 74, "atk": 48, "def": 76, "spa": 143, "spd": 101, "spe": 124},
        "bst": 566, "za_exclusive": True,
    },
    # --- Gen 7 Pokemon (DLC) ---
    {
        "pokemon_id": 740, "pokemon": "Crabominable",
        "mega_name_en": "Mega Crabominable", "mega_name_it": "Mega Crabominable",
        "type1": "Fighting", "type2": "Ice",
        "type1_it": "Lotta", "type2_it": "Ghiaccio",
        "ability": "", "ability_it": "",
        "mega_stone": "Crabominite", "mega_stone_it": "Crabominite",
        "stats": {"hp": 97, "atk": 157, "def": 122, "spa": 62, "spd": 107, "spe": 33},
        "bst": 578, "za_exclusive": True,
    },
    {
        "pokemon_id": 768, "pokemon": "Golisopod",
        "mega_name_en": "Mega Golisopod", "mega_name_it": "Mega Golisopod",
        "type1": "Bug", "type2": "Steel",
        "type1_it": "Coleottero", "type2_it": "Acciaio",
        "ability": "", "ability_it": "",
        "mega_stone": "Golisopodite", "mega_stone_it": "Golisopodite",
        "stats": {"hp": 75, "atk": 150, "def": 175, "spa": 70, "spd": 120, "spe": 40},
        "bst": 630, "za_exclusive": True,
    },
    {
        "pokemon_id": 801, "pokemon": "Magearna",
        "mega_name_en": "Mega Magearna", "mega_name_it": "Mega Magearna",
        "type1": "Steel", "type2": "Fairy",
        "type1_it": "Acciaio", "type2_it": "Folletto",
        "ability": "", "ability_it": "",
        "mega_stone": "Magearnite", "mega_stone_it": "Magearnite",
        "stats": {"hp": 80, "atk": 125, "def": 115, "spa": 170, "spd": 115, "spe": 95},
        "bst": 700, "za_exclusive": True,
    },
    {
        "pokemon_id": 801, "pokemon": "Magearna",
        "mega_name_en": "Mega Magearna (Original Color)",
        "mega_name_it": "Mega Magearna (Colore Originale)",
        "type1": "Steel", "type2": "Fairy",
        "type1_it": "Acciaio", "type2_it": "Folletto",
        "ability": "", "ability_it": "",
        "mega_stone": "Magearnite", "mega_stone_it": "Magearnite",
        "stats": {"hp": 80, "atk": 125, "def": 115, "spa": 170, "spd": 115, "spe": 95},
        "bst": 700, "za_exclusive": True,
    },
    {
        "pokemon_id": 807, "pokemon": "Zeraora",
        "mega_name_en": "Mega Zeraora", "mega_name_it": "Mega Zeraora",
        "type1": "Electric", "type2": "",
        "type1_it": "Elettro", "type2_it": "",
        "ability": "", "ability_it": "",
        "mega_stone": "Zeraorite", "mega_stone_it": "Zeraorite",
        "stats": {"hp": 88, "atk": 157, "def": 75, "spa": 147, "spd": 80, "spe": 153},
        "bst": 700, "za_exclusive": True,
    },
    # --- Gen 9 Pokemon (DLC) ---
    {
        "pokemon_id": 952, "pokemon": "Scovillain",
        "mega_name_en": "Mega Scovillain", "mega_name_it": "Mega Scovillain",
        "type1": "Grass", "type2": "Fire",
        "type1_it": "Erba", "type2_it": "Fuoco",
        "ability": "", "ability_it": "",
        "mega_stone": "Scovillainite", "mega_stone_it": "Scovillainite",
        "stats": {"hp": 65, "atk": 138, "def": 85, "spa": 138, "spd": 85, "spe": 75},
        "bst": 586, "za_exclusive": True,
    },
    {
        "pokemon_id": 970, "pokemon": "Glimmora",
        "mega_name_en": "Mega Glimmora", "mega_name_it": "Mega Glimmora",
        "type1": "Rock", "type2": "Poison",
        "type1_it": "Roccia", "type2_it": "Veleno",
        "ability": "", "ability_it": "",
        "mega_stone": "Glimmorite", "mega_stone_it": "Glimmorite",
        "stats": {"hp": 83, "atk": 90, "def": 105, "spa": 150, "spd": 96, "spe": 101},
        "bst": 625, "za_exclusive": True,
    },
    {
        "pokemon_id": 978, "pokemon": "Tatsugiri",
        "mega_name_en": "Mega Tatsugiri (Curly)",
        "mega_name_it": "Mega Tatsugiri (Ricciolo)",
        "type1": "Dragon", "type2": "Water",
        "type1_it": "Drago", "type2_it": "Acqua",
        "ability": "", "ability_it": "",
        "mega_stone": "Tatsugirite", "mega_stone_it": "Tatsugirite",
        "stats": {"hp": 68, "atk": 65, "def": 90, "spa": 135, "spd": 125, "spe": 92},
        "bst": 575, "za_exclusive": True,
    },
    {
        "pokemon_id": 978, "pokemon": "Tatsugiri",
        "mega_name_en": "Mega Tatsugiri (Droopy)",
        "mega_name_it": "Mega Tatsugiri (Pendente)",
        "type1": "Dragon", "type2": "Water",
        "type1_it": "Drago", "type2_it": "Acqua",
        "ability": "", "ability_it": "",
        "mega_stone": "Tatsugirite", "mega_stone_it": "Tatsugirite",
        "stats": {"hp": 68, "atk": 65, "def": 90, "spa": 135, "spd": 125, "spe": 92},
        "bst": 575, "za_exclusive": True,
    },
    {
        "pokemon_id": 978, "pokemon": "Tatsugiri",
        "mega_name_en": "Mega Tatsugiri (Stretchy)",
        "mega_name_it": "Mega Tatsugiri (Allungato)",
        "type1": "Dragon", "type2": "Water",
        "type1_it": "Drago", "type2_it": "Acqua",
        "ability": "", "ability_it": "",
        "mega_stone": "Tatsugirite", "mega_stone_it": "Tatsugirite",
        "stats": {"hp": 68, "atk": 65, "def": 90, "spa": 135, "spd": 125, "spe": 92},
        "bst": 575, "za_exclusive": True,
    },
    {
        "pokemon_id": 998, "pokemon": "Baxcalibur",
        "mega_name_en": "Mega Baxcalibur", "mega_name_it": "Mega Baxcalibur",
        "type1": "Dragon", "type2": "Ice",
        "type1_it": "Drago", "type2_it": "Ghiaccio",
        "ability": "", "ability_it": "",
        "mega_stone": "Baxcaliburite", "mega_stone_it": "Baxcaliburite",
        "stats": {"hp": 115, "atk": 175, "def": 117, "spa": 105, "spd": 101, "spe": 87},
        "bst": 700, "za_exclusive": True,
    },
]
